version: '3'

services:
  mongo:
    image: mongo:latest 
    container_name: mongoDB
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=bot-db

  tg-bot:
    build: .
    command: /app/bot-run.sh
    container_name: tg-bot
    volumes:
      - ./src:/app/src
      - ./.env:/app/.env
    depends_on:
      - mongo 
